default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: sattar
  password: sattar
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Blogging_Haven_development

test:
  <<: *default
  database: Blogging_Haven_test

production:
  <<: *default
  database: Blogging_Haven_production
  username: Blogging_Haven
  password: <%= ENV["BLOGGING_HAVEN_DATABASE_PASSWORD"] %>
